# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# CSV Read

In [4]:
sales_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Laptop_Sales_Dataset_10000.csv",encoding= 'unicode_escape')

In [8]:
secondary_df= pd.read_csv(r"C:\Users\Dell\Desktop\work\Laptop_Secondary_Market_Dataset_10000.csv",encoding= 'unicode_escape')

In [10]:
warranty_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Warranty_Dataset_5000.csv",encoding= 'unicode_escape')

In [11]:
manufacturing_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Manufacturing_Dataset_10000.csv",encoding= 'unicode_escape')

### Showing Top 5

In [15]:
sales_df.head(5)

,Sales_ID,SKU_ID,Sale_Date,Store_ID,Sales_Channel,Customer_ID,Quantity,Unit_Price,Discount,Final_Amount,Payment_Method
0,SAL00001,SKU00001,10-05-2024,STR045,Online,CUST00001,1,57112,10,"51,400.80",Credit Card
1,SAL00002,SKU00002,04-09-2025,STR022,Online,CUST00002,1,67285,10,"60,556.50",EMI
2,SAL00003,SKU00003,16-11-2024,STR027,Online,CUST00003,1,40949,20,"32,759.20",Cash
3,SAL00004,SKU00004,16-10-2023,STR049,Retail Store,CUST00004,1,39544,15,"33,612.40",Cash
4,SAL00005,SKU00005,22-08-2024,STR006,Retail Store,CUST00005,1,90369,0,"90,369.00",EMI

In [16]:
secondary_df.head(5)

,SecondaryMarket_ID,SKU_ID,Original_Purchase_Date,Resale_Date,Resale_Price,Condition,Seller_Type,Buyer_Type,Platform,City,Transaction_Status
0,SMR00001,SKU00001,24-09-2023,29-09-2025,"29,072.00",Refurbished,Refurbisher,Business,Facebook Marketplace,Bengaluru,Cancelled
1,SMR00002,SKU00002,19-05-2023,17-01-2024,"32,657.00",Refurbished,Refurbisher,Individual,Amazon Renewed,Delhi,Completed
2,SMR00003,SKU00003,28-02-2024,08-11-2024,"35,507.00",Good,Retailer,Student,Amazon Renewed,Delhi,Completed
3,SMR00004,SKU00004,06-11-2022,24-03-2025,"24,983.00",Fair,Individual,Student,Cashify,Kolkata,Cancelled
4,SMR00005,SKU00005,05-05-2023,18-10-2025,"32,696.00",Refurbished,Retailer,Business,Facebook Marketplace,Chennai,Returned

In [17]:
warranty_df.head(5)

,SKU_ID,Product Name,Brand,Model,Manufacturing Date,Component,Component Cost,Warranty Period,Failure Rate,Manufacturing Cost
0,SKU000001,MacBook Pro 16,Apple,AP-2858,23-01-2023,RAM,"2,227",36,1.18,"45,822"
1,SKU000002,Swift 3,Acer,AC-6532,20-02-2022,Keyboard,"8,453",24,3.29,"49,028"
2,SKU000003,MacBook Air,Apple,AP-4843,10-11-2021,Keyboard,"1,861",48,4.89,"25,260"
3,SKU000004,MacBook Air,Apple,AP-6444,23-02-2024,Cooling Fan,"2,352",24,3.26,"49,239"
4,SKU000005,Aspire 5,Acer,AC-1213,04-07-2024,Cooling Fan,"7,222",48,7.26,"32,168"

In [18]:
manufacturing_df.head(5)

,SKU_ID,Product Name,Brand,Model,Manufacturing Date,Component,Component Cost,Warranty Period,Failure Rate,Manufacturing Cost
0,SKU000001,Nitro 5,Acer,AC-9075,18-09-2024,Keyboard,"11,228",24,6.38,"56,093"
1,SKU000002,Inspiron 15,Dell,DE-5811,14-03-2022,Keyboard,"2,667",24,4.48,"40,397"
2,SKU000003,Inspiron 15,Dell,DE-2914,07-08-2020,Adapter,"10,635",48,3.55,"49,202"
3,SKU000004,MacBook Pro,Apple,AP-6164,13-07-2025,Motherboard,"2,640",36,0.81,"41,481"
4,SKU000005,Aspire 5,Acer,AC-6560,20-12-2025,Adapter,"1,295",48,7.17,"52,005"

### Table Info

In [19]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sales_ID        10000 non-null  object
 1   SKU_ID          10000 non-null  object
 2   Sale_Date       10000 non-null  object
 3   Store_ID        10000 non-null  object
 4   Sales_Channel   10000 non-null  object
 5   Customer_ID     10000 non-null  object
 6   Quantity        10000 non-null  int64
 7   Unit_Price      10000 non-null  int64
 8   Discount        10000 non-null  int64
 9   Final_Amount    10000 non-null  object
 10  Payment_Method  10000 non-null  object
dtypes: int64(3), object(8)
memory usage: 859.5+ KB

In [20]:
secondary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SecondaryMarket_ID      10000 non-null  object
 1   SKU_ID                  10000 non-null  object
 2   Original_Purchase_Date  10000 non-null  object
 3   Resale_Date             10000 non-null  object
 4   Resale_Price            10000 non-null  object
 5   Condition               10000 non-null  object
 6   Seller_Type             10000 non-null  object
 7   Buyer_Type              10000 non-null  object
 8   Platform                10000 non-null  object
 9   City                    10000 non-null  object
 10  Transaction_Status      10000 non-null  object
dtypes: object(11)
memory usage: 859.5+ KB

In [21]:
warranty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SKU_ID              5000 non-null   object
 1   Product Name        5000 non-null   object
 2   Brand               5000 non-null   object
 3   Model               5000 non-null   object
 4   Manufacturing Date  5000 non-null   object
 5   Component           5000 non-null   object
 6   Component Cost      5000 non-null   object
 7   Warranty Period     5000 non-null   int64
 8   Failure Rate        5000 non-null   float64
 9   Manufacturing Cost  5000 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 390.8+ KB

In [22]:
manufacturing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SKU_ID              10000 non-null  object
 1   Product Name        10000 non-null  object
 2   Brand               10000 non-null  object
 3   Model               10000 non-null  object
 4   Manufacturing Date  10000 non-null  object
 5   Component           10000 non-null  object
 6   Component Cost      10000 non-null  object
 7   Warranty Period     10000 non-null  int64
 8   Failure Rate        10000 non-null  float64
 9   Manufacturing Cost  10000 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 781.4+ KB

# Data Cleaning

### Duplicate Remove

In [23]:
sales_df.drop_duplicates(inplace=True)
manufacturing_df.drop_duplicates(inplace=True)
warranty_df.drop_duplicates(inplace=True)
secondary_df.drop_duplicates(inplace=True)

### Missing Values Check

In [25]:
sales_df.isnull().sum()

SKU_ID                0
Product Name          0
Brand                 0
Model                 0
Manufacturing Date    0
Component             0
Component Cost        0
Warranty Period       0
Failure Rate          0
Manufacturing Cost    0
dtype: int64

In [26]:
manufacturing_df.isnull().sum()

SKU_ID                0
Product Name          0
Brand                 0
Model                 0
Manufacturing Date    0
Component             0
Component Cost        0
Warranty Period       0
Failure Rate          0
Manufacturing Cost    0
dtype: int64

In [27]:
warranty_df.isnull().sum()

SKU_ID                0
Product Name          0
Brand                 0
Model                 0
Manufacturing Date    0
Component             0
Component Cost        0
Warranty Period       0
Failure Rate          0
Manufacturing Cost    0
dtype: int64

In [28]:
secondary_df.isnull().sum()

SecondaryMarket_ID        0
SKU_ID                    0
Original_Purchase_Date    0
Resale_Date               0
Resale_Price              0
Condition                 0
Seller_Type               0
Buyer_Type                0
Platform                  0
City                      0
Transaction_Status        0
dtype: int64

### Describe

In [29]:
sales_df.describe()

       Quantity     Unit_Price      Discount
count   10000.0   10000.000000  10000.000000
mean        1.0   74891.022600      9.931000
std         0.0   26031.757941      7.067548
min         1.0   30004.000000      0.000000
25%         1.0   52453.750000      5.000000
50%         1.0   74939.000000     10.000000
75%         1.0   97574.250000     15.000000
max         1.0  119994.000000     20.000000

In [30]:
warranty_df.describe()

       Warranty Period  Failure Rate
count      5000.000000   5000.000000
mean         30.055200      4.240852
std          13.355232      2.144864
min          12.000000      0.500000
25%          24.000000      2.397500
50%          24.000000      4.220000
75%          36.000000      6.070000
max          48.000000      8.000000

In [31]:
manufacturing_df.describe()

       Warranty Period  Failure Rate
count     10000.000000  10000.000000
mean         29.989200      4.019355
std          13.416001      2.208595
min          12.000000      0.200000
25%          12.000000      2.110000
50%          24.000000      4.045000
75%          36.000000      5.940000
max          48.000000      7.800000

In [32]:
secondary_df.describe()

,SecondaryMarket_ID,SKU_ID,Original_Purchase_Date,Resale_Date,Resale_Price,Condition,Seller_Type,Buyer_Type,Platform,City,Transaction_Status
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,10000,900,1564,8388,5,3,3,6,10,3
top,SMR00001,SKU00001,22-06-2023,16-08-2024,"57,169.00",Refurbished,Individual,Individual,Local Store,Kochi,Returned
freq,1,1,22,21,5,2045,3379,3349,1693,1049,3440