# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Read as CSV

In [2]:
sales_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Laptop_Sales_Dataset_10000.csv",encoding= 'unicode_escape')

In [3]:
secondary_df= pd.read_csv(r"C:\Users\Dell\Desktop\work\Laptop_Secondary_Market_Dataset_10000.csv",encoding= 'unicode_escape')

In [4]:
warranty_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Warranty_Dataset_5000.csv",encoding= 'unicode_escape')

In [5]:
manufacturing_df = pd.read_csv(r"C:\Users\Dell\Desktop\work\Manufacturing_Dataset_10000.csv",encoding= 'unicode_escape')

# Bivarites Analysis

## For Sales

### Sales_Channel + Payment_Method + Final_Amount = Revenue Analysis

In [16]:
sales_df.groupby(
    ["Sales_Channel", "Payment_Method"]
)["Final_Amount"].sum().reset_index()

   Sales_Channel Payment_Method  Final_Amount
0    Distributor           Cash      37396614
1    Distributor    Credit Card      37378010
2    Distributor     Debit Card      38281638
3    Distributor            EMI      34710565
4    Distributor    Net Banking      37359472
5    Distributor            UPI      37771227
6         Online           Cash      37699319
7         Online    Credit Card      38622037
8         Online     Debit Card      38024372
9         Online            EMI      38766454
10        Online    Net Banking      37431650
11        Online            UPI      36567355
12  Retail Store           Cash      35988988
13  Retail Store    Credit Card      38664215
14  Retail Store     Debit Card      37705561
15  Retail Store            EMI      38850966
16  Retail Store    Net Banking      37784571
17  Retail Store            UPI      35506392

### For Secondary

### Condition + Platform + Resale_Price = Resale Analysis

In [17]:
secondary_df.groupby(
    ["Condition", "Platform"]
)["Resale_Price"].sum().reset_index()

      Condition              Platform  Resale_Price
0     Excellent        Amazon Renewed      15142490
1     Excellent               Cashify      15439277
2     Excellent  Facebook Marketplace      14369094
3     Excellent  Flipkart Refurbished      16675511
4     Excellent           Local Store      14727869
5     Excellent                   OLX      14092127
6          Fair        Amazon Renewed       7484841
7          Fair               Cashify       7262576
8          Fair  Facebook Marketplace       6558915
9          Fair  Flipkart Refurbished       7025297
10         Fair           Local Store       7200585
11         Fair                   OLX       7437313
12         Good        Amazon Renewed      11687246
13         Good               Cashify      11489031
14         Good  Facebook Marketplace      10914039
15         Good  Flipkart Refurbished      11432774
16         Good           Local Store      12108088
17         Good                   OLX      10977031
18     Like New        Amazon Renewed      18525316
19     Like New               Cashify      17378600
20     Like New  Facebook Marketplace      19990750
21     Like New  Flipkart Refurbished      19822369
22     Like New           Local Store      17942640
23     Like New                   OLX      18136761
24  Refurbished        Amazon Renewed       9401028
25  Refurbished               Cashify      10321068
26  Refurbished  Facebook Marketplace      10902264
27  Refurbished  Flipkart Refurbished       9145227
28  Refurbished           Local Store      10982841
29  Refurbished                   OLX      10672489

### For manufacturing

### Brand + Component + Failure_Rate = Failure Analysis

In [8]:
manufacturing_df.groupby(
    ["Brand", "Component"]
)["Failure Rate"].mean().reset_index()

     Brand    Component  Failure Rate
0     ASUS      Adapter      4.121604
1     ASUS      Battery      3.852880
2     ASUS          CPU      3.735389
3     ASUS  Cooling Fan      3.888824
4     ASUS      Display      3.690824
5     ASUS          GPU      4.248263
6     ASUS     Keyboard      4.033232
7     ASUS  Motherboard      4.012312
8     ASUS          RAM      4.242909
9     ASUS          SSD      3.919780
10    Acer      Adapter      4.011419
11    Acer      Battery      3.822252
12    Acer          CPU      3.979195
13    Acer  Cooling Fan      3.865367
14    Acer      Display      4.084251
15    Acer          GPU      4.041734
16    Acer     Keyboard      3.905380
17    Acer  Motherboard      4.090462
18    Acer          RAM      3.904172
19    Acer          SSD      4.277273
20   Apple      Adapter      3.959130
21   Apple      Battery      4.116770
22   Apple          CPU      3.838261
23   Apple  Cooling Fan      3.998816
24   Apple      Display      4.143415
25   Apple          GPU      4.121047
26   Apple     Keyboard      4.037134
27   Apple  Motherboard      4.050385
28   Apple          RAM      3.720838
29   Apple          SSD      3.879119
30    Dell      Adapter      3.806868
31    Dell      Battery      3.932774
32    Dell          CPU      4.370852
33    Dell  Cooling Fan      3.945585
34    Dell      Display      4.171687
35    Dell          GPU      4.125000
36    Dell     Keyboard      3.981277
37    Dell  Motherboard      3.976272
38    Dell          RAM      4.123559
39    Dell          SSD      3.682260
40      HP      Adapter      4.017394
41      HP      Battery      4.291950
42      HP          CPU      4.103563
43      HP  Cooling Fan      3.798671
44      HP      Display      4.057697
45      HP          GPU      4.091243
46      HP     Keyboard      4.026012
47      HP  Motherboard      3.867931
48      HP          RAM      4.199740
49      HP          SSD      4.079811
50  Lenovo      Adapter      4.082784
51  Lenovo      Battery      3.851145
52  Lenovo          CPU      4.025394
53  Lenovo  Cooling Fan      4.094968
54  Lenovo      Display      4.133067
55  Lenovo          GPU      4.178249
56  Lenovo     Keyboard      3.929536
57  Lenovo  Motherboard      4.149405
58  Lenovo          RAM      4.232824
59  Lenovo          SSD      4.276624

### For Warranty

In [9]:
warranty_df.groupby(
    ["Brand", "Component"]
)["Failure Rate"].mean().reset_index()

     Brand    Component  Failure Rate
0     ASUS      Adapter      3.868218
1     ASUS      Battery      3.772500
2     ASUS  Cooling Fan      4.539570
3     ASUS      Display      4.317905
4     ASUS     Keyboard      4.228829
5     ASUS  Motherboard      4.236522
6     ASUS          RAM      4.272667
7     ASUS          SSD      4.300476
8     Acer      Adapter      4.526783
9     Acer      Battery      4.118478
10    Acer  Cooling Fan      4.552536
11    Acer      Display      4.055340
12    Acer     Keyboard      4.353514
13    Acer  Motherboard      3.849505
14    Acer          RAM      4.837344
15    Acer          SSD      4.130707
16   Apple      Adapter      3.926095
17   Apple      Battery      4.328571
18   Apple  Cooling Fan      4.208316
19   Apple      Display      4.359508
20   Apple     Keyboard      4.259722
21   Apple  Motherboard      4.677477
22   Apple          RAM      4.120583
23   Apple          SSD      4.021957
24    Dell      Adapter      4.274466
25    Dell      Battery      4.076800
26    Dell  Cooling Fan      3.950000
27    Dell      Display      4.036186
28    Dell     Keyboard      4.263945
29    Dell  Motherboard      4.304545
30    Dell          RAM      4.334211
31    Dell          SSD      4.186277
32      HP      Adapter      4.425810
33      HP      Battery      4.349588
34      HP  Cooling Fan      3.962632
35      HP      Display      3.853118
36      HP     Keyboard      4.277549
37      HP  Motherboard      4.108362
38      HP          RAM      4.215089
39      HP          SSD      4.119725
40  Lenovo      Adapter      4.577679
41  Lenovo      Battery      4.288584
42  Lenovo  Cooling Fan      4.144902
43  Lenovo      Display      4.200435
44  Lenovo     Keyboard      4.263204
45  Lenovo  Motherboard      4.325102
46  Lenovo          RAM      4.473505
47  Lenovo          SSD      4.204526

### string to float to int(secondary)

In [13]:
secondary_df["Resale_Price"].dtype

dtype('int64')

In [11]:
secondary_df["Resale_Price"] = (
    secondary_df["Resale_Price"]
    .str.replace(",", "", regex=False)
)

secondary_df["Resale_Price"] = pd.to_numeric(
    secondary_df["Resale_Price"],
    errors="coerce"
)

In [12]:
secondary_df["Resale_Price"] = secondary_df["Resale_Price"].astype(int)

### string to float to int (sales)

In [14]:
sales_df["Final_Amount"] = (
    sales_df["Final_Amount"]
    .str.replace(",", "", regex=False)
)

sales_df["Final_Amount"] = pd.to_numeric(
    sales_df["Final_Amount"],
    errors="coerce"
)

In [15]:
sales_df["Final_Amount"] = sales_df["Final_Amount"].astype(int)